# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'current_lab.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CurrentLab(object):
    def setupUi(self, CurrentLab):
        CurrentLab.setObjectName("CurrentLab")
        CurrentLab.resize(445, 359)
        font = QtGui.QFont()
        font.setPointSize(10)
        CurrentLab.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(CurrentLab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(CurrentLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.c_lab_acronym = QtWidgets.QLineEdit(CurrentLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.c_lab_acronym.setFont(font)
        self.c_lab_acronym.setObjectName("c_lab_acronym")
        self.verticalLayout.addWidget(self.c_lab_acronym)
        self.label = QtWidgets.QLabel(CurrentLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.c_status = QtWidgets.QComboBox(CurrentLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.c_status.setFont(font)
        self.c_status.setObjectName("c_status")
        self.verticalLayout.addWidget(self.c_status)
        self.label_12 = QtWidgets.QLabel(CurrentLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.c_begin_date = QtWidgets.QDateEdit(CurrentLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.c_begin_date.setFont(font)
        self.c_begin_date.setObjectName("c_begin_date")
        self.verticalLayout.addWidget(self.c_begin_date)
        self.label_13 = QtWidgets.QLabel(CurrentLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.c_lab_comment = QtWidgets.QTextEdit(CurrentLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.c_lab_comment.setFont(font)
        self.c_lab_comment.setObjectName("c_lab_comment")
        self.verticalLayout.addWidget(self.c_lab_comment)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtWidgets.QPushButton(CurrentLab)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.clear_btn = QtWidgets.QPushButton(CurrentLab)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_2.addWidget(self.clear_btn)
        self.cancel_btn = QtWidgets.QPushButton(CurrentLab)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(CurrentLab)
        QtCore.QMetaObject.connectSlotsByName(CurrentLab)

    def retranslateUi(self, CurrentLab):
        _translate = QtCore.QCoreApplication.translate
        CurrentLab.setWindowTitle(_translate("CurrentLab", "Current Lab 1"))
        self.label_10.setText(_translate("CurrentLab", "Lab Acronym **"))
        self.c_lab_acronym.setToolTip(_translate("CurrentLab", "<html><head/><body><p>Experimentalist laboratory acronym</p></body></html>"))
        self.label.setText(_translate("CurrentLab", "Status *"))
        self.c_status.setToolTip(_translate("CurrentLab", "<html><head/><body><p>Experimentalist\'s status in this laboratory</p></body></html>"))
        self.label_12.setText(_translate("CurrentLab", "Beginning date **"))
        self.c_begin_date.setToolTip(_translate("CurrentLab", "<html><head/><body><p>Format: YYYY-MM-DD, beginning date of the experimentalist in this laboratory (<span style=\" font-weight:600;\">needed for DOI</span>)</p></body></html>"))
        self.label_13.setText(_translate("CurrentLab", "Additional information"))
        self.c_lab_comment.setToolTip(_translate("CurrentLab", "<html><head/><body><p>Any additional information on this laboratory</p></body></html>"))
        self.buttonBox.setText(_translate("CurrentLab", "Save and Close"))
        self.clear_btn.setText(_translate("CurrentLab", "Clear this form"))
        self.cancel_btn.setText(_translate("CurrentLab", "Close without change"))
