# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'previous_lab.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreviousLab(object):
    def setupUi(self, PreviousLab):
        PreviousLab.setObjectName("PreviousLab")
        PreviousLab.resize(445, 420)
        font = QtGui.QFont()
        font.setPointSize(10)
        PreviousLab.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreviousLab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(PreviousLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.p_lab_acronym = QtWidgets.QLineEdit(PreviousLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.p_lab_acronym.setFont(font)
        self.p_lab_acronym.setObjectName("p_lab_acronym")
        self.verticalLayout.addWidget(self.p_lab_acronym)
        self.label_2 = QtWidgets.QLabel(PreviousLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.p_status = QtWidgets.QComboBox(PreviousLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.p_status.setFont(font)
        self.p_status.setObjectName("p_status")
        self.verticalLayout.addWidget(self.p_status)
        self.label_12 = QtWidgets.QLabel(PreviousLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.p_begin_date = QtWidgets.QDateEdit(PreviousLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.p_begin_date.setFont(font)
        self.p_begin_date.setObjectName("p_begin_date")
        self.verticalLayout.addWidget(self.p_begin_date)
        self.label = QtWidgets.QLabel(PreviousLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.p_end_date = QtWidgets.QDateEdit(PreviousLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.p_end_date.setFont(font)
        self.p_end_date.setObjectName("p_end_date")
        self.verticalLayout.addWidget(self.p_end_date)
        self.label_13 = QtWidgets.QLabel(PreviousLab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.p_lab_comment = QtWidgets.QTextEdit(PreviousLab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.p_lab_comment.setFont(font)
        self.p_lab_comment.setObjectName("p_lab_comment")
        self.verticalLayout.addWidget(self.p_lab_comment)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtWidgets.QPushButton(PreviousLab)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.clear_btn = QtWidgets.QPushButton(PreviousLab)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_2.addWidget(self.clear_btn)
        self.cancel_btn = QtWidgets.QPushButton(PreviousLab)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PreviousLab)
        QtCore.QMetaObject.connectSlotsByName(PreviousLab)

    def retranslateUi(self, PreviousLab):
        _translate = QtCore.QCoreApplication.translate
        PreviousLab.setWindowTitle(_translate("PreviousLab", "Previous Lab 1"))
        self.label_10.setText(_translate("PreviousLab", "Lab Acronym **"))
        self.p_lab_acronym.setToolTip(_translate("PreviousLab", "<html><head/><body><p>Experimentalist laboratory acronym</p></body></html>"))
        self.label_2.setText(_translate("PreviousLab", "Status *"))
        self.p_status.setToolTip(_translate("PreviousLab", "<html><head/><body><p>Experimentalist\'s status in this laboratory</p></body></html>"))
        self.label_12.setText(_translate("PreviousLab", "Beginning date **"))
        self.p_begin_date.setToolTip(_translate("PreviousLab", "<html><head/><body><p>Format: YYYY-MM-DD, beginning date of the experimentalist in this laboratory (<span style=\" font-weight:600;\">needed for DOI</span>)</p></body></html>"))
        self.label.setText(_translate("PreviousLab", "Ending date **"))
        self.p_end_date.setToolTip(_translate("PreviousLab", "<html><head/><body><p>Format: YYYY-MM-DD, ending date of the experimentalist in this laboratory (<span style=\" font-weight:600;\">needed for DOI</span>)</p></body></html>"))
        self.label_13.setText(_translate("PreviousLab", "Additional information"))
        self.p_lab_comment.setToolTip(_translate("PreviousLab", "<html><head/><body><p>Any additional information on this laboratory</p></body></html>"))
        self.buttonBox.setText(_translate("PreviousLab", "Save and Close"))
        self.clear_btn.setText(_translate("PreviousLab", "Clear this form"))
        self.cancel_btn.setText(_translate("PreviousLab", "Close without change"))
