# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.header.setFont(font)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout_3.addWidget(self.header)
        self.XML_type_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.XML_type_label.setFont(font)
        self.XML_type_label.setTextFormat(QtCore.Qt.AutoText)
        self.XML_type_label.setScaledContents(False)
        self.XML_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.XML_type_label.setObjectName("XML_type_label")
        self.verticalLayout_3.addWidget(self.XML_type_label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 9, 0, 1, 1)
        self.email = QtWidgets.QLineEdit(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.gridLayout_8.addWidget(self.email, 8, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setToolTip("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 3, 0, 1, 1)
        self.first_name = QtWidgets.QLineEdit(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.first_name.setFont(font)
        self.first_name.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.first_name.setObjectName("first_name")
        self.gridLayout_8.addWidget(self.first_name, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 7, 0, 1, 1)
        self.comments_contact = QtWidgets.QTextEdit(self.tab_6)
        self.comments_contact.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.comments_contact.setFont(font)
        self.comments_contact.setOverwriteMode(True)
        self.comments_contact.setTabStopWidth(80)
        self.comments_contact.setObjectName("comments_contact")
        self.gridLayout_8.addWidget(self.comments_contact, 12, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 13, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_6)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 5, 0, 1, 1)
        self.phone = QtWidgets.QLineEdit(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.phone.setFont(font)
        self.phone.setObjectName("phone")
        self.gridLayout_8.addWidget(self.phone, 10, 0, 1, 1)
        self.family_name = QtWidgets.QLineEdit(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.family_name.setFont(font)
        self.family_name.setObjectName("family_name")
        self.gridLayout_8.addWidget(self.family_name, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 11, 0, 1, 1)
        self.state = QtWidgets.QComboBox(self.tab_6)
        self.state.setObjectName("state")
        self.gridLayout_8.addWidget(self.state, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_ISNI_2 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ISNI_2.setFont(font)
        self.label_ISNI_2.setObjectName("label_ISNI_2")
        self.gridLayout_9.addWidget(self.label_ISNI_2, 3, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.label_ResearcherID_2 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ResearcherID_2.setFont(font)
        self.label_ResearcherID_2.setObjectName("label_ResearcherID_2")
        self.gridLayout_9.addWidget(self.label_ResearcherID_2, 5, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.ORCID = QtWidgets.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.ORCID.setFont(font)
        self.ORCID.setObjectName("ORCID")
        self.gridLayout_9.addWidget(self.ORCID, 2, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_ORCIDE_2 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ORCIDE_2.setFont(font)
        self.label_ORCIDE_2.setObjectName("label_ORCIDE_2")
        self.gridLayout_9.addWidget(self.label_ORCIDE_2, 1, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.ISNI = QtWidgets.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.ISNI.setFont(font)
        self.ISNI.setObjectName("ISNI")
        self.gridLayout_9.addWidget(self.ISNI, 4, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_9.addWidget(self.label_31, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.ResearcherID = QtWidgets.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.ResearcherID.setFont(font)
        self.ResearcherID.setObjectName("ResearcherID")
        self.gridLayout_9.addWidget(self.ResearcherID, 6, 0, 1, 1, QtCore.Qt.AlignTop)
        self.ScopusAuthorID = QtWidgets.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.ScopusAuthorID.setFont(font)
        self.ScopusAuthorID.setObjectName("ScopusAuthorID")
        self.gridLayout_9.addWidget(self.ScopusAuthorID, 8, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_ScopusAuthorID_2 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ScopusAuthorID_2.setFont(font)
        self.label_ScopusAuthorID_2.setObjectName("label_ScopusAuthorID_2")
        self.gridLayout_9.addWidget(self.label_ScopusAuthorID_2, 7, 0, 1, 1, QtCore.Qt.AlignBottom)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 9, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_32 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.tab_8)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.link_name_1 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_name_1.setFont(font)
        self.link_name_1.setObjectName("link_name_1")
        self.gridLayout_10.addWidget(self.link_name_1, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_8)
        self.label_35.setMinimumSize(QtCore.QSize(0, 0))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_10.addWidget(self.label_35, 1, 0, 1, 1)
        self.link_url_1 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_url_1.setFont(font)
        self.link_url_1.setObjectName("link_url_1")
        self.gridLayout_10.addWidget(self.link_url_1, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.label_36 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_2.addWidget(self.label_36)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_37 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 0, 0, 1, 1)
        self.link_name_2 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_name_2.setFont(font)
        self.link_name_2.setObjectName("link_name_2")
        self.gridLayout_11.addWidget(self.link_name_2, 0, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_8)
        self.label_38.setMinimumSize(QtCore.QSize(0, 0))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 1, 0, 1, 1)
        self.link_url_2 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_url_2.setFont(font)
        self.link_url_2.setObjectName("link_url_2")
        self.gridLayout_11.addWidget(self.link_url_2, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.label_39 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_2.addWidget(self.label_39)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 0, 0, 1, 1)
        self.link_name_3 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_name_3.setFont(font)
        self.link_name_3.setObjectName("link_name_3")
        self.gridLayout_12.addWidget(self.link_name_3, 0, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setMinimumSize(QtCore.QSize(0, 0))
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 1, 0, 1, 1)
        self.link_url_3 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_url_3.setFont(font)
        self.link_url_3.setObjectName("link_url_3")
        self.gridLayout_12.addWidget(self.link_url_3, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_12)
        self.label_42 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_2.addWidget(self.label_42)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_43 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_13.addWidget(self.label_43, 0, 0, 1, 1)
        self.link_name_4 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_name_4.setFont(font)
        self.link_name_4.setObjectName("link_name_4")
        self.gridLayout_13.addWidget(self.link_name_4, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_8)
        self.label_44.setMinimumSize(QtCore.QSize(0, 0))
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_13.addWidget(self.label_44, 1, 0, 1, 1)
        self.link_url_4 = QtWidgets.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.link_url_4.setFont(font)
        self.link_url_4.setObjectName("link_url_4")
        self.gridLayout_13.addWidget(self.link_url_4, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_45 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_14.addWidget(self.label_45, 1, 0, 1, 1)
        self.c_lab_btn_1 = QtWidgets.QPushButton(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c_lab_btn_1.setFont(font)
        self.c_lab_btn_1.setObjectName("c_lab_btn_1")
        self.gridLayout_14.addWidget(self.c_lab_btn_1, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem3, 6, 0, 1, 1)
        self.c_lab_btn_3 = QtWidgets.QPushButton(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c_lab_btn_3.setFont(font)
        self.c_lab_btn_3.setObjectName("c_lab_btn_3")
        self.gridLayout_14.addWidget(self.c_lab_btn_3, 4, 0, 1, 1)
        self.c_lab_btn_2 = QtWidgets.QPushButton(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c_lab_btn_2.setFont(font)
        self.c_lab_btn_2.setObjectName("c_lab_btn_2")
        self.gridLayout_14.addWidget(self.c_lab_btn_2, 3, 0, 1, 1)
        self.c_lab_btn_4 = QtWidgets.QPushButton(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c_lab_btn_4.setFont(font)
        self.c_lab_btn_4.setObjectName("c_lab_btn_4")
        self.gridLayout_14.addWidget(self.c_lab_btn_4, 5, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_14.addWidget(self.label_46, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_47 = QtWidgets.QLabel(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_8.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_8.addWidget(self.label_48)
        self.p_lab_btn_1 = QtWidgets.QPushButton(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_lab_btn_1.setFont(font)
        self.p_lab_btn_1.setObjectName("p_lab_btn_1")
        self.verticalLayout_8.addWidget(self.p_lab_btn_1)
        self.p_lab_btn_2 = QtWidgets.QPushButton(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_lab_btn_2.setFont(font)
        self.p_lab_btn_2.setObjectName("p_lab_btn_2")
        self.verticalLayout_8.addWidget(self.p_lab_btn_2)
        self.p_lab_btn_3 = QtWidgets.QPushButton(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_lab_btn_3.setFont(font)
        self.p_lab_btn_3.setObjectName("p_lab_btn_3")
        self.verticalLayout_8.addWidget(self.p_lab_btn_3)
        self.p_lab_btn_4 = QtWidgets.QPushButton(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_lab_btn_4.setFont(font)
        self.p_lab_btn_4.setObjectName("p_lab_btn_4")
        self.verticalLayout_8.addWidget(self.p_lab_btn_4)
        self.p_lab_btn_5 = QtWidgets.QPushButton(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_lab_btn_5.setFont(font)
        self.p_lab_btn_5.setObjectName("p_lab_btn_5")
        self.verticalLayout_8.addWidget(self.p_lab_btn_5)
        self.p_lab_btn_6 = QtWidgets.QPushButton(self.tab_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_lab_btn_6.setFont(font)
        self.p_lab_btn_6.setObjectName("p_lab_btn_6")
        self.verticalLayout_8.addWidget(self.p_lab_btn_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_10, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_3.addWidget(self.label_49)
        self.buttonBox = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.first_name)
        MainWindow.setTabOrder(self.first_name, self.family_name)
        MainWindow.setTabOrder(self.family_name, self.state)
        MainWindow.setTabOrder(self.state, self.email)
        MainWindow.setTabOrder(self.email, self.phone)
        MainWindow.setTabOrder(self.phone, self.comments_contact)
        MainWindow.setTabOrder(self.comments_contact, self.ORCID)
        MainWindow.setTabOrder(self.ORCID, self.ISNI)
        MainWindow.setTabOrder(self.ISNI, self.ResearcherID)
        MainWindow.setTabOrder(self.ResearcherID, self.ScopusAuthorID)
        MainWindow.setTabOrder(self.ScopusAuthorID, self.link_name_1)
        MainWindow.setTabOrder(self.link_name_1, self.link_url_1)
        MainWindow.setTabOrder(self.link_url_1, self.link_name_2)
        MainWindow.setTabOrder(self.link_name_2, self.link_url_2)
        MainWindow.setTabOrder(self.link_url_2, self.link_name_3)
        MainWindow.setTabOrder(self.link_name_3, self.link_url_3)
        MainWindow.setTabOrder(self.link_url_3, self.link_name_4)
        MainWindow.setTabOrder(self.link_name_4, self.link_url_4)
        MainWindow.setTabOrder(self.link_url_4, self.c_lab_btn_1)
        MainWindow.setTabOrder(self.c_lab_btn_1, self.c_lab_btn_2)
        MainWindow.setTabOrder(self.c_lab_btn_2, self.c_lab_btn_3)
        MainWindow.setTabOrder(self.c_lab_btn_3, self.c_lab_btn_4)
        MainWindow.setTabOrder(self.c_lab_btn_4, self.p_lab_btn_1)
        MainWindow.setTabOrder(self.p_lab_btn_1, self.p_lab_btn_2)
        MainWindow.setTabOrder(self.p_lab_btn_2, self.p_lab_btn_3)
        MainWindow.setTabOrder(self.p_lab_btn_3, self.p_lab_btn_4)
        MainWindow.setTabOrder(self.p_lab_btn_4, self.p_lab_btn_5)
        MainWindow.setTabOrder(self.p_lab_btn_5, self.p_lab_btn_6)
        MainWindow.setTabOrder(self.p_lab_btn_6, self.buttonBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "SSHADE XML generator"))
        self.XML_type_label.setText(_translate("MainWindow", "<html><head/><body><p>Experimentalist template</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "Phone"))
        self.email.setToolTip(_translate("MainWindow", "<html><head/><body>Experimentalist Email</body></html>"))
        self.label_28.setText(_translate("MainWindow", "Experimentalist\'s information"))
        self.label_29.setText(_translate("MainWindow", "First name **"))
        self.label_26.setText(_translate("MainWindow", "Family name **"))
        self.first_name.setToolTip(_translate("MainWindow", "<html><head/><body><p>Experimentalist First (Given) name</p></body></html>"))
        self.first_name.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Email *"))
        self.comments_contact.setToolTip(_translate("MainWindow", "<html><head/><body><p>Any additional information about the experimentalist</p></body></html>"))
        self.label.setText(_translate("MainWindow", "State **"))
        self.phone.setToolTip(_translate("MainWindow", "<html><head/><body>Experimental phone in international format</body></html>"))
        self.family_name.setToolTip(_translate("MainWindow", "<html><head/><body>Experimentalist Family (Last) name</body></html>"))
        self.label_30.setText(_translate("MainWindow", "Any additional information"))
        self.state.setToolTip(_translate("MainWindow", "<html><head/><body><p>State of activity of the experimentalist</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "1 Info"))
        self.label_ISNI_2.setText(_translate("MainWindow", "ISNI"))
        self.label_ResearcherID_2.setText(_translate("MainWindow", "Researcher ID"))
        self.ORCID.setToolTip(_translate("MainWindow", "<html><head/><body><p>Experimentalist ORCID, Open Researcher and Contributor ID, if available</p></body></html>"))
        self.label_ORCIDE_2.setText(_translate("MainWindow", "ORCID identifier *"))
        self.ISNI.setToolTip(_translate("MainWindow", "<html><head/><body><p>Experimentalist ISNI (International Standard Name Identifier) if available</p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "Experimentalist\'s identifiers"))
        self.ResearcherID.setToolTip(_translate("MainWindow", "<html><head/><body><p>Experimentalist Researcher ID if available</p></body></html>"))
        self.ScopusAuthorID.setToolTip(_translate("MainWindow", "<html><head/><body><p>Experimentalist Scopus Author ID if available</p></body></html>"))
        self.label_ScopusAuthorID_2.setText(_translate("MainWindow", "Scopus Author ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "2 Idents"))
        self.label_32.setText(_translate("MainWindow", "Experimentalist professional web page"))
        self.label_33.setText(_translate("MainWindow", "Experimentalist\'s web page(s)"))
        self.link_name_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Web page title, i.e. John Doe\'s professional web page</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "name"))
        self.label_35.setText(_translate("MainWindow", "URL "))
        self.link_url_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>web address of the page</p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "Experimentalist personal web page"))
        self.label_37.setText(_translate("MainWindow", "name"))
        self.link_name_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Web page title, i.e. John Doe\'s strange science</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "URL "))
        self.link_url_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>web address of the page</p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "Other web page (project, ...)"))
        self.label_40.setText(_translate("MainWindow", "name"))
        self.link_name_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Web page title, i.e. John Doe\'s Gray Matter project</p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "URL "))
        self.link_url_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>web address of the page</p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "Other web page (ResearchGate, LinkedIn, ...)"))
        self.label_43.setText(_translate("MainWindow", "name"))
        self.link_name_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Web page title, i.e. John Doe\'s LinkedIn page</p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "URL "))
        self.link_url_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>web address of the page</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "3 Links"))
        self.label_45.setText(_translate("MainWindow", "Please, provide all laboratories in which you are currently affiliated. \n"
"At least one laboratory must be given"))
        self.c_lab_btn_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add a current laboratory</p></body></html>"))
        self.c_lab_btn_1.setText(_translate("MainWindow", "Your main current laboratory"))
        self.c_lab_btn_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add one more current laboratory</p></body></html>"))
        self.c_lab_btn_3.setText(_translate("MainWindow", "Current Lab 3"))
        self.c_lab_btn_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add another current laboratory</p></body></html>"))
        self.c_lab_btn_2.setText(_translate("MainWindow", "Current Lab 2"))
        self.c_lab_btn_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add one more current laboratory</p></body></html>"))
        self.c_lab_btn_4.setText(_translate("MainWindow", "Current Lab 4"))
        self.label_46.setText(_translate("MainWindow", "Experimentalist\'s current laboratories"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "4 Current"))
        self.label_47.setText(_translate("MainWindow", "Experimentalist\'s previous laboratories"))
        self.label_48.setText(_translate("MainWindow", "Please, provide all your previously affiliated laboratories\n"
"in which you were producing lab data"))
        self.p_lab_btn_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add a previous laboratory</p></body></html>"))
        self.p_lab_btn_1.setText(_translate("MainWindow", "Previous Lab 1"))
        self.p_lab_btn_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add another previous laboratory</p></body></html>"))
        self.p_lab_btn_2.setText(_translate("MainWindow", "Previous Lab 2"))
        self.p_lab_btn_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add one more previous laboratory</p></body></html>"))
        self.p_lab_btn_3.setText(_translate("MainWindow", "Previous Lab 3"))
        self.p_lab_btn_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add one more previous laboratory</p></body></html>"))
        self.p_lab_btn_4.setText(_translate("MainWindow", "Previous Lab 4"))
        self.p_lab_btn_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add one more previous laboratory</p></body></html>"))
        self.p_lab_btn_5.setText(_translate("MainWindow", "Previous Lab 5"))
        self.p_lab_btn_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add one more previous laboratory</p></body></html>"))
        self.p_lab_btn_6.setText(_translate("MainWindow", "Previous Lab 6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "5 Previous"))
        self.label_49.setText(_translate("MainWindow", "**: This information is mandatory\n"
"*: This information is recommended"))
        self.buttonBox.setText(_translate("MainWindow", "Generate the XML file with this information"))
